import { OnDestroy, OnInit } from '@angular/core';
import { BehaviorSubject } from 'rxjs';
import { PageInterface } from '../../interfaces';
import { Comment } from '../../models';
import { AaaUserService } from '../../services/aaa-user';
import { DashBoardCommentControllerService } from '../../services/dash-board-comment-controller';
import { CommentFormComponent } from './comment-form/comment-form.component';
export declare class CommentsPopoverComponent implements OnInit, OnDestroy {
    private dashBoardCommentControllerService;
    aaaUserService: AaaUserService;
    entityId: string;
    newCommentForm: CommentFormComponent;
    apiComments: PageInterface<Comment>;
    isLoading: boolean;
    isRefreshing: boolean;
    searchUser$: BehaviorSubject<string>;
    private _searchUser$;
    constructor(dashBoardCommentControllerService: DashBoardCommentControllerService, aaaUserService: AaaUserService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    popoverShown(): Promise<void>;
    searchTerm(searchTerm: string): void;
    toggleEdit(comment: Comment): void;
    onSubmit(formValue: any): void;
    updateSubmit(formValue: any, comment: Comment): Promise<void>;
    createComment(message: string): Promise<void>;
    updateComment(commentId: string, message: string): Promise<void>;
    deleteComment(commentId: string): Promise<void>;
    private loadComments;
}
