import { ChangeDetectorRef, EventEmitter } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { ChangeDetectableComponentBase } from '../../../change-detectable-component-base';
import { FileUploadComponent } from '../file-upload/file-upload.component';
import { SimpleFileUploadConfig } from './simple-file-upload-config.model';
import { SimpleFileUploadItem } from './simple-file-upload-item.model';
export declare class SimpleFileUploadComponent extends ChangeDetectableComponentBase implements ControlValueAccessor {
    protected changeDetectorRef: ChangeDetectorRef;
    id: string;
    prefixText: string;
    linkText: string;
    suffixText: string;
    attachments: any[];
    files: SimpleFileUploadItem[];
    config: SimpleFileUploadConfig;
    isMultiple: boolean;
    disabled: boolean;
    hasDescription: boolean;
    maxFileSize: number;
    uploadHidden: boolean;
    afterFilesSelected: EventEmitter<SimpleFileUploadItem[]>;
    deleteAttachment: EventEmitter<any>;
    clickAttachment: EventEmitter<any>;
    fileUploadComponent: FileUploadComponent;
    constructor(changeDetectorRef: ChangeDetectorRef);
    onAfterFilesSelected(files: File[], text?: string): void;
    onRemoveFile(index: number): void;
    onClickAttachment(attachment: any): void;
    onDeleteAttachment(attachment: any): void;
    writeValue(value: any): void;
    registerOnChange(): void;
    registerOnTouched(): void;
}
